repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.12
  hooks:
  - id: terraform-fmt
  - id: terraform-validate
  - id: tflint
