name: CI

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - README.md
  push:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - README.md

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2
    - name: Check formatting
      run: terraform fmt -check -recursive

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: "1.17"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: CheckCallerIdentity
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github
    - name: Test
      working-directory: test
      run: go test -v ./...
