name: Continuous-integration

on:
  pull_request: { }
  push:
    branches:
    - main

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
