name: CI

on:
  pull_request: { }
  push:
    branches:
    - main

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform-version: "0.14"
    - name: Check formatting
      run: terraform fmt -check -recursive
